# Generated by Django 3.0.4 on 2020-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(null=True),
        ),
    ]
